plugins {
    id 'com.android.application'
}

android {
    namespace 'com.hakamo.drugs'
    compileSdk 35

    defaultConfig {
        applicationId 'com.hakamo.drugs'
        minSdk 23
        targetSdk 35
        versionCode 81
        versionName '8.1'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['META-INF/DEPENDENCIES', 'META-INF/LICENSE', 'META-INF/LICENSE.txt', 'META-INF/NOTICE', 'META-INF/NOTICE.txt']
        }
    }
}
